Fixed compilation error with Visual Studio
When compiling with Visual Studio one gets the error

  C:\Libraries\github\spotify\annoy\src\annoylib.h(1070,11): error C4996: 'open':
  The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _open.

The functions open(), ... are not supported by MSVS 2019.
Note that they are defined by the POSIX standard, not by the C++ standard.
However, MSVS 2019 provides POSIX compatible functions named _open(), ...
See also: https://learn.microsoft.com/en-us/cpp/c-runtime-library/compatibility?view=msvc-170